name: Update README Activity

on:
  schedule:
    - cron: '0 */12 * * *' # Se actualiza cada 12 horas
  workflow_dispatch: # Esto te permite darle al botón "Run" manualmente

jobs:
  build:
    runs-on: ubuntu-latest # Usa los servidores de GitHub, no necesitas runners propios
    permissions:
      contents: write # Esto es vital para que pueda editar tu README
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Actualización de actividad reciente"
          MAX_LINES: 5
